baseURL = "https://calgaryaikikai.com"
languageCode = "en"
title = "Calgary Aikikai"
[module]
  [[module.imports]]
    path = "github.com/nunocoracao/blowfish/v2"

[permalinks]
  blog = "/blog/:slug/"
  seminars = "/seminars/:slug/"
  pages = "/pages/:slug/"

[taxonomies]
  tag = "tags"
  category = "categories"

[outputs]
  home = ["HTML", "RSS", "JSON"]
  section = ["HTML", "RSS"]

[sitemap]
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"

[privacy]
  [privacy.youtube]
    privacyEnhanced = true
