colorScheme = "navy"
defaultTheme = "system"
enableSearch = true
enableOpenGraph = true
enableTwitterCards = true
enableJSONLD = true
robotsNoIndex = false

showBreadcrumbs = true
showReadingTime = false
showWordCount = false
showDate = true
showTableOfContents = false
showPagination = true
showRelatedContent = false
showEdit = false
showHeadingAnchors = false
showCodeCopyButtons = false

[homepage]
  layout = "background"
  homepageImage = "images/dojo-hero.jpg"
  showRecent = true
  showRecentItems = 4
  showMoreLink = true
  showMoreLinkDest = "/blog/"
  layoutBackgroundBlur = true

[Author]
  name = "Calgary Aikikai"
  headline = "An aikido community in Calgary since 1980"

[article]
  showDate = true
  showDateUpdated = false
  showAuthor = false
  showReadingTime = false
  showTableOfContents = false
  showPagination = true
  showRelatedContent = false
  showEdit = false

[list]
  showBreadcrumbs = false
  showSummary = true
  groupByYear = false

[footer]
  showCopyright = true
  showThemeAttribution = false
  showAppearanceSwitcher = true
  showScrollToTop = true
